# Generated by Django 5.1.1 on 2025-12-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedfile',
            name='tag',
        ),
    ]
